version: "3.8"

services:
  golang_crud:
    container_name: golang_crud
    build:
      context: ./build/app
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - ./build/db/.env
    expends_on: # サービス起動順: db -> go
      - db
    volumes:
      - type: bind
        source: .
        target: /go/app
    networks:
      - golang_test_network

db:
  container_name: db
  build:
    context: ./build/db
    dockerfile: Dockerfile
  tty: true
  platform: linux/amd64
  ports:
    - 3306:3306
  env_file:
    - ./build/db/.env
  volumes:
    - type: volumes
      source: mysql_test_volume
      target: /var/lib/mysql
    - type: bind
      source: ./build/db/init
      target: /docker-entrypoint-initdb.d
  networks:
    - golang_test_network

volumes:
  mysql_test_volume:
    name: mysql_test_volume

networks:
  golang_test_network:
    external: true
